name: Docker
on:
  push:
    branches: main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push producer image
        id: docker_build_producer
        uses: docker/build-push-action@v2
        with:
          context: code/producer
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kafka-python-prod-demo:latest
          push: ${{ github.event_name != 'pull_request' }}
          
      - name: Show image digest
        run: echo ${{ steps.docker_build_producer.outputs.digest }}